# Generated by Django 5.2.17 on 2026-09-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerprofile',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical travel budget, paired with budget_period.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='budget_period',
            field=models.CharField(blank=True, choices=[('day', 'Per day'), ('week', 'Per week'), ('month', 'Per month')], max_length=10),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='home_country',
            field=models.CharField(blank=True, help_text="Where you usually travel from, e.g. 'Brazil'.", max_length=200),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='travelers_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many people you usually travel with, including yourself.', null=True),
        ),
    ]
