# Generated by Django 5.2.17 on 2026-09-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_travelerprofile_budget_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerprofile',
            name='budget_currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar (USD)'), ('AED', 'UAE Dirham (AED)'), ('ARS', 'Argentine Peso (ARS)'), ('AUD', 'Australian Dollar (AUD)'), ('BRL', 'Brazilian Real (BRL)'), ('CAD', 'Canadian Dollar (CAD)'), ('CHF', 'Swiss Franc (CHF)'), ('CLP', 'Chilean Peso (CLP)'), ('CNY', 'Chinese Yuan (CNY)'), ('COP', 'Colombian Peso (COP)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('INR', 'Indian Rupee (INR)'), ('JPY', 'Japanese Yen (JPY)'), ('KRW', 'South Korean Won (KRW)'), ('MXN', 'Mexican Peso (MXN)'), ('NOK', 'Norwegian Krone (NOK)'), ('NZD', 'New Zealand Dollar (NZD)'), ('PLN', 'Polish Zloty (PLN)'), ('SEK', 'Swedish Krona (SEK)'), ('SGD', 'Singapore Dollar (SGD)'), ('THB', 'Thai Baht (THB)'), ('TRY', 'Turkish Lira (TRY)'), ('ZAR', 'South African Rand (ZAR)')], help_text='The currency budget_amount is stated in - required alongside it.', max_length=3),
        ),
    ]
