# Generated by Django 5.2.17 on 2026-09-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_configure_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt', 'Português'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('fr', 'Français')], help_text='Explicit UI language choice, applied on every device once set.', max_length=10),
        ),
    ]
