# Generated by Django 5.2.17 on 2026-08-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('trip_type', models.CharField(choices=[('beach', 'Beach'), ('city', 'City'), ('nature', 'Nature'), ('culture', 'Culture')], max_length=20)),
                ('cost_of_living', models.PositiveSmallIntegerField(choices=[(1, 'Very low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very high')])),
                ('best_season', models.CharField(max_length=200)),
                ('worst_season', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('points_of_interest', models.JSONField(default=list, help_text="List of point-of-interest names, e.g. ['Tower of Belem'].")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
