# Generated by Django 5.2.17 on 2026-09-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryEntryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='The destination country these requirements apply to.', max_length=200, unique=True)),
                ('visa_required_nationalities', models.JSONField(blank=True, default=list, help_text="Nationalities that generally need a visa for a typical short tourist stay in this country, e.g. ['Brazil', 'Argentina']. Not exhaustive - see visa_notes for waiver programs/nuance.")),
                ('visa_notes', models.TextField(blank=True, help_text='Free-form nuance - visa-waiver program names, e-visa availability, typical stay length allowed.')),
                ('vaccine_requirements', models.JSONField(blank=True, default=list, help_text="Vaccines required or recommended for entry, e.g. ['Yellow Fever - required if arriving from an endemic country'].")),
                ('insurance_required', models.BooleanField(default=False, help_text='Whether travel/health insurance is a formal entry requirement, not just a recommendation.')),
                ('insurance_notes', models.TextField(blank=True)),
                ('other_requirements', models.JSONField(blank=True, default=list, help_text="Other entry requirements, e.g. ['Minimum 6 months passport validity', 'Proof of onward travel'].")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'country entry requirement',
                'verbose_name_plural': 'country entry requirements',
                'ordering': ['country'],
            },
        ),
    ]
