# Generated by Django 5.2.17 on 2026-09-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_countryentryrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryentryrequirement',
            name='videos',
            field=models.JSONField(blank=True, default=list, help_text="Travel videos for this country, as [url, language_code] pairs, e.g. [['https://www.youtube.com/watch?v=...', 'EN']]. language_code is whatever language the video itself is actually in, not necessarily one of the site's own supported UI languages. Sourced from web search (2026-09-07), not an official tourism catalog - same 'general knowledge, not verified' caveat already applied to the rest of this model."),
        ),
    ]
