# Generated by Django 5.2.17 on 2026-08-30 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registered', 'User registered'), ('profile_completed', 'Traveler profile completed'), ('travel_question_submitted', 'Travel question submitted'), ('recommendation_generated', 'Recommendation generated'), ('trip_created', 'Trip created'), ('feedback_submitted', 'Feedback submitted')], max_length=40)),
                ('anonymized_ip', models.GenericIPAddressField(blank=True, help_text='Set only for anonymous events (last IPv4 octet / last 80 IPv6 bits zeroed before storage - see analytics.services._anonymize_ip).', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Small structured payload (e.g. destination slug, rating). Never free text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Set for authenticated events. Null for anonymous events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx'), models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_9a87e5_idx')],
            },
        ),
    ]
