# Generated by Django 5.2.17 on 2026-09-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='conversation_key',
            field=models.CharField(blank=True, db_index=True, help_text="The exact string ai.memory.conversation_key() produces for this event, when it happened inside a chat conversation - lets chat-related events be joined together. NOT itself a per-conversation identifier for an authenticated user (it's stable for that user's entire chat history, chat-history:user:{pk}) - the warehouse layer splits it into real conversation episodes via a 30-minute-inactivity session gap. Null for events with no conversation context (e.g. registration).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='locale',
            field=models.CharField(blank=True, help_text='request.LANGUAGE_CODE at the time of the event, when available.', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('profile_completed', 'Traveler profile completed'), ('travel_question_submitted', 'Travel question submitted'), ('recommendation_generated', 'Recommendation generated'), ('trip_created', 'Trip created'), ('feedback_submitted', 'Feedback submitted'), ('destination_selected', 'Destination selected (Choose this trip)'), ('signup_started', 'Signup started'), ('anonymous_user_authenticated', 'Anonymous visitor authenticated'), ('llm_request_completed', 'LLM request completed'), ('provider_request_completed', 'External provider request completed')], max_length=40),
        ),
    ]
