# Generated by Django 5.2.17 on 2026-09-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_create_warehouse_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimDestination',
            fields=[
                ('destination_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('trip_type', models.CharField(max_length=20)),
                ('cost_of_living', models.SmallIntegerField()),
                ('has_video', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_destinations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField(null=True)),
                ('preferred_language', models.CharField(max_length=10)),
                ('is_staff', models.BooleanField()),
                ('home_country', models.CharField(max_length=200, null=True)),
                ('preferred_cost_of_living', models.SmallIntegerField(null=True)),
                ('has_traveler_profile', models.BooleanField()),
            ],
            options={
                'db_table': 'dim_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAiRequest',
            fields=[
                ('event_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=40)),
                ('operation', models.CharField(max_length=100, null=True)),
                ('success', models.BooleanField(null=True)),
                ('latency_ms', models.DecimalField(decimal_places=1, max_digits=12, null=True)),
                ('error_type', models.CharField(max_length=100, null=True)),
                ('conversation_key', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fact_ai_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactConversation',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('conversation_key', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('last_event_at', models.DateTimeField()),
                ('user_id', models.BigIntegerField(null=True)),
                ('locale', models.CharField(max_length=10, null=True)),
                ('message_count', models.IntegerField()),
                ('reached_recommendation', models.BooleanField()),
                ('reached_selection', models.BooleanField()),
                ('reached_trip_created', models.BooleanField()),
                ('reached_feedback', models.BooleanField()),
            ],
            options={
                'db_table': 'fact_conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactFeedback',
            fields=[
                ('feedback_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('destination_id', models.BigIntegerField(null=True)),
                ('destination_slug', models.CharField(max_length=50, null=True)),
                ('rating', models.SmallIntegerField()),
                ('tags', models.JSONField()),
                ('trip_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fact_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactRecommendation',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('conversation_key', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('destination_slug', models.CharField(max_length=50)),
                ('recommended_at', models.DateTimeField()),
                ('was_selected', models.BooleanField()),
                ('was_saved', models.BooleanField()),
            ],
            options={
                'db_table': 'fact_recommendations',
                'managed': False,
            },
        ),
    ]
