# Generated by Django 5.2.17 on 2026-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_dimdestination_dimuser_factairequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductMetrics',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('conversations_started', models.PositiveIntegerField(default=0)),
                ('unique_anonymous_conversations', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('conversations_reached_recommendation', models.PositiveIntegerField(default=0)),
                ('recommendations_generated', models.PositiveIntegerField(default=0)),
                ('destinations_recommended', models.PositiveIntegerField(default=0)),
                ('destinations_selected', models.PositiveIntegerField(default=0)),
                ('destinations_saved', models.PositiveIntegerField(default=0)),
                ('signups_started', models.PositiveIntegerField(default=0)),
                ('signups_completed', models.PositiveIntegerField(default=0)),
                ('anonymous_visitors_authenticated', models.PositiveIntegerField(default=0)),
                ('feedback_submitted', models.PositiveIntegerField(default=0)),
                ('feedback_positive', models.PositiveIntegerField(default=0)),
                ('ai_requests_total', models.PositiveIntegerField(default=0)),
                ('ai_requests_failed', models.PositiveIntegerField(default=0)),
                ('ai_latency_p50_ms', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('ai_latency_p95_ms', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('ai_latency_p99_ms', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'daily product metrics',
                'ordering': ['-date'],
            },
        ),
    ]
