# Generated by Django 5.2.17 on 2026-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_dailyproductmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('profile_completed', 'Traveler profile completed'), ('travel_question_submitted', 'Travel question submitted'), ('recommendation_generated', 'Recommendation generated'), ('trip_created', 'Trip created'), ('feedback_submitted', 'Feedback submitted'), ('destination_selected', 'Destination selected (Choose this trip)'), ('signup_started', 'Signup started'), ('anonymous_user_authenticated', 'Anonymous visitor authenticated'), ('llm_request_completed', 'LLM request completed'), ('provider_request_completed', 'External provider request completed'), ('accommodation_outbound_click', 'Accommodation search link clicked')], max_length=40),
        ),
    ]
