# Generated by Django 5.2.17 on 2026-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_fact_recommendations_accommodation_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAcquisitionFunnel',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('conversation_key', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('touch_type', models.CharField(max_length=10, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('medium', models.CharField(max_length=100, null=True)),
                ('campaign', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=100, null=True)),
                ('term', models.CharField(max_length=100, null=True)),
                ('touched_at', models.DateTimeField()),
                ('reached_planning', models.BooleanField()),
                ('reached_recommendation', models.BooleanField()),
                ('reached_accommodation_click', models.BooleanField()),
            ],
            options={
                'db_table': 'fact_acquisition_funnel',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('profile_completed', 'Traveler profile completed'), ('travel_question_submitted', 'Travel question submitted'), ('recommendation_generated', 'Recommendation generated'), ('trip_created', 'Trip created'), ('feedback_submitted', 'Feedback submitted'), ('destination_selected', 'Destination selected (Choose this trip)'), ('signup_started', 'Signup started'), ('anonymous_user_authenticated', 'Anonymous visitor authenticated'), ('llm_request_completed', 'LLM request completed'), ('provider_request_completed', 'External provider request completed'), ('accommodation_outbound_click', 'Accommodation search link clicked'), ('acquisition_captured', 'Acquisition touch captured')], max_length=40),
        ),
    ]
