# Generated by Django 5.2.17 on 2026-09-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("travel", "0003_countryentryrequirement_videos"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("network", models.CharField(choices=[("cj", "CJ Affiliate")], max_length=20)),
                (
                    "advertiser_id",
                    models.CharField(
                        help_text="The network's own advertiser/merchant id (e.g. a CJ CID).",
                        max_length=50,
                    ),
                ),
                ("advertiser_name", models.CharField(blank=True, max_length=200)),
                (
                    "link_id",
                    models.CharField(
                        help_text="The network's own id for this link.", max_length=50
                    ),
                ),
                ("link_name", models.CharField(blank=True, max_length=255)),
                (
                    "destination_url",
                    models.URLField(
                        help_text="The advertiser's own destination URL, before tracking.",
                        max_length=1000,
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(
                        help_text="The real, trackable link to actually send a traveler to.",
                        max_length=1000,
                    ),
                ),
                (
                    "targeted_countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Country names/codes the advertiser targeted this link for.",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        help_text="The Wanderes destination this link was searched for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_links",
                        to="travel.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("network", "link_id"), name="unique_affiliate_link_per_network"
                    )
                ],
            },
        ),
    ]
