# Generated by Django 5.2.17 on 2026-08-29 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_rate', models.PositiveSmallIntegerField(choices=[(1, 'Much cheaper than usual'), (2, 'Cheaper than usual'), (3, 'Typical price'), (4, 'More expensive than usual'), (5, 'Much more expensive than usual')], help_text='How this price compares to the historical price for this stay.')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('link', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=200)),
                ('departure_at', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('leg_order', models.PositiveSmallIntegerField(default=1, help_text="Order of this leg within the trip's itinerary (1, 2, 3...).")),
                ('is_connecting', models.BooleanField(default=False, help_text='True if this leg is a connecting flight, not the first/only leg.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_rate', models.PositiveSmallIntegerField(choices=[(1, 'Much cheaper than usual'), (2, 'Cheaper than usual'), (3, 'Typical price'), (4, 'More expensive than usual'), (5, 'Much more expensive than usual')], help_text='How this price compares to the historical price for this route.')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'ordering': ['leg_order'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of positive/negative tags.')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='travel.destination')),
            ],
        ),
    ]
