# Generated by Django 5.2.17 on 2026-08-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_travelhistoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, help_text="A short nickname, e.g. 'Summer in Lisbon'.", max_length=200),
        ),
    ]
