# Generated by Django 5.2.17 on 2026-09-03 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_countryentryrequirement'),
        ('trips', '0004_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of positive/negative tags.', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='travelhistoryentry',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_history', to='travel.destination', verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='travelhistoryentry',
            name='visited_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Approximate year of the visit, if known.', null=True, verbose_name='visited year'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='travel.destination', verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, help_text="A short nickname, e.g. 'Summer in Lisbon'.", max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='status'),
        ),
    ]
